### ISSUE TITLE
没有speech方法 报错

### ISSUE THREAD

**Issue by wrhsd1** [xy3xy3/VoiceChatgpt#1]
Fatal error: Uncaught Error: Call to undefined method Orhanerday\OpenAi\OpenAi::speech() in inc.php:41 Stack trace: #0 /chat.php(37): speech() #1 {main} thrown in inc.php on line 41
请问大佬 这个报错什么意思

**Comment by xy3xy3** [comment]
可能需要下载我这个程序的/[vendor](https://github.com/xy3xy3/VoiceChatgpt/tree/master/vendor)/[orhanerday](https://github.com/xy3xy3/VoiceChatgpt/tree/master/vendor/orhanerday)
/open-ai/
因为原版这个包还没加入speech功能，是我自己加上去的；
如果你是composer install安装的
需要在`/vendor/orhanerday/open-ai/src
/URL.php`加入
```
    public static function speechUrl(): string
    {
        return self::OPEN_AI_URL . "/audio/speech";
    }
```
在`/vendor/orhanerday/open-ai/src
/OpenAi.php`加入
```
    public function speech($opts)
    {
        $url = Url::speechUrl();
        $this->baseUrl($url);

        return $this->sendRequest($url, 'POST', $opts);
    }
```

**Comment by wrhsd1** [comment]
可以了 感谢大佬回复
